### PR TITLE
Add Windows Support (Visual Studio)

### PR DESCRIPTION
**Pull request by cconlon**
This PR adds Windows support for wolfCrypt JNI/JCE using Visual Studio, for consistency and use with main wolfSSL Visual Studio projects.

Build instructions are located in `IDE/WIN/README.md`

Tested on Microsoft Windows 10 Pro with Visual Studio 2019.

### CODE REVIEW

**Review by JacobBarthelmeh — CHANGES_REQUESTED** [review]
The "Additional Include Directories" path to include jni.h is hard set. When testing I had used a different include path and openjdk version. Changing the include path in the project to `%JAVA_HOME%\include;%JAVA_HOME%\include\win32` resolved it for me.

Right now when first opening the solution it defaults to the FIPS build, should this be the case?

**Comment by JacobBarthelmeh** [comment]
I also hit a snag when trying to run the ant test after building it:

```
D:\work\wolfcrypt-jni>ant test-win32-debug
ANT_OPTS is set to  -Djava.security.manager=allow
Buildfile: D:\work\wolfcrypt-jni\build.xml

setup-win32-debug:

antTestWindowsCheck:

test:
   [delete] Deleting directory D:\work\wolfcrypt-jni\build\test
    [mkdir] Created dir: D:\work\wolfcrypt-jni\build\test

set-build-debug:

debug-javac-flags:

build-test:
    [javac] Compiling 40 source files to D:\work\wolfcrypt-jni\build\test
    [junit] Running com.wolfssl.provider.jce.test.WolfJCETestSuite
    [junit] Tests run: 0, Failures: 0, Errors: 11, Skipped: 0, Time elapsed: 0.064 sec

BUILD FAILED
D:\work\wolfcrypt-jni\build.xml:421: Test com.wolfssl.provider.jce.test.WolfJCETestSuite failed

Total time: 1 second
```

**Comment by cconlon** [comment]
@JacobBarthelmeh Thanks!  I fixed the hard-coded include paths for Win32 builds, good catch.  I had adjusted the x64 build to use `$(JAVA_HOME)`, but had missed the Win32.  I also made this same fix and force pushed to the wolfssljni PR (https://github.com/wolfSSL/wolfssljni/pull/125).

I don't see an option to set the default build configuration.  I think Visual Studio might decide which one to select by default based on their own naming logic?

For the failed ant test, if you look in the file ` build/reports/TEST-com.wolfssl.provider.jce.test.WolfJCETestSuite.txt` after the test failure, do you see errors similar to ` JCE cannot authenticate the provider wolfJCE`?  If so, the Java installation requires the JCE provider to be signed by an Oracle code signing certificate in order to allow access into some of the JCE classes from the Java Security APIs.  I can send you a pre-signed .JAR file to test with for this scenario.  Our wolfCrypt JNI/JCE releases include signed JAR files for this use case scenario.

**Comment by JacobBarthelmeh** [comment]
@cconlon looks like maybe a missmatch from me trying to run the win32 version on my system:

```
Testcase: com.wolfssl.provider.jce.test.WolfCryptMessageDigestMd5Test took 0 sec
	Caused an ERROR
D:\work\wolfssl\DLL Debug\Win32\wolfssl.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
java.lang.UnsatisfiedLinkError: D:\work\wolfssl\DLL Debug\Win32\wolfssl.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2669)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1907)
	at com.wolfssl.wolfcrypt.FeatureDetect.<clinit>(FeatureDetect.java:91)
	at com.wolfssl.provider.jce.WolfCryptProvider.<init>(WolfCryptProvider.java:40)
	at com.wolfssl.provider.jce.test.WolfCryptMessageDigestMd5Test.testProviderInstallationAtRuntime(WolfCryptMessageDigestMd5Test.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

Testing with the x64 build passes ok.

**Comment by cconlon** [comment]
@JacobBarthelmeh Ok, thanks.  That makes sense.  Users will need to compile the correct build for their architecture (Win32 or x64).

**Review by JacobBarthelmeh — APPROVED** [review]

**Pull request merged**
